### PR TITLE
Added mindmap for Plan 9

### PR DESCRIPTION
**Pull request by Miko4**

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Thank you @Miko4 

You are actually the first person to propose to add a new mind map and a good one at that. 🎊

There are few things that are a bit wrong but we will merge it for now and we can fix them. Thank you again.

**Comment by nglgzz** [comment]
The JSON wasn't valid, there was a comma that wasn't supposed to be there on line 146. Other than that it looks good. Just for curiosity, how did you find the coordinates?

**Comment by Miko4** [comment]
Oops. I took the next best map and used that coordinates. In this case unix.json.

**Comment by nglgzz** [comment]
Oh cool, didn't think about that.

**Pull request merged**
